version: "3.3"
services:
  database:
    image: beercan1989/arm-mysql
    ports: ["3306:3306"]
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret

  api:
    build: api
    ports: ["80:80"]
    volumes:
      - "./api:/var/www"
